version: '3.8'

services:
  backend:
    build:
      context: ./backendAPI
      dockerfile: Dockerfile
    container_name: exercise_api
    ports:
      - "8000:8000"
    environment:
      - POETRY_NO_INTERACTION=1
      - POETRY_VIRTUALENVS_CREATE=false
    command: poetry run uvicorn src.index:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backendAPI:/app
